import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    // This is optional because it's only used in development.
    // See https://next-auth.js.org/deployment.
    NODE_ENV: z.enum(["development", "production"]),
    NEXTAUTH_URL: z.string().url().optional(),
    NEXTAUTH_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    SMTP_FROM: z.string().optional(),
    // POSTMARK_API_TOKEN: z.string().min(1),
    // POSTMARK_SIGN_IN_TEMPLATE: z.string().min(1),
    // POSTMARK_ACTIVATION_TEMPLATE: z.string().min(1),
    STRIPE_API_KEY: z.string().min(1),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    STRIPE_PRO_MONTHLY_PLAN_ID: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    SUPABASE_DB_PASSWORD: z.string().min(1),
    SUPABASE_API_KEY: z.string().min(1),
    BING_SEARCH_API_KEY: z.string().min(1),
    BING_ENDPOINT: z.string().min(1),
    PINECONE_ENVIRONMENT: z.string().min(1),
    PINECONE_API_KEY: z.string().min(1),
    PINECONE_INDEX_NAME: z.string().min(1),
    PINECONE_NAMESPACE: z.string().min(1),
    SCREENSHOT_API: z.string().min(1),
    SCREENSHOT_SECRET: z.string().min(1),
    SCREENSHOT_ENABLED: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().min(1),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    DATABASE_URL: process.env.DATABASE_URL,
    SMTP_FROM: process.env.SMTP_FROM,
    // POSTMARK_API_TOKEN: process.env.POSTMARK_API_TOKEN,
    // POSTMARK_SIGN_IN_TEMPLATE: process.env.POSTMARK_SIGN_IN_TEMPLATE,
    // POSTMARK_ACTIVATION_TEMPLATE: process.env.POSTMARK_ACTIVATION_TEMPLATE,
    STRIPE_API_KEY: process.env.STRIPE_API_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_PRO_MONTHLY_PLAN_ID: process.env.STRIPE_PRO_MONTHLY_PLAN_ID,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    SUPABASE_DB_PASSWORD: process.env.SUPABASE_DB_PASSWORD,
    SUPABASE_API_KEY: process.env.SUPABASE_API_KEY,
    BING_SEARCH_API_KEY: process.env.BING_SEARCH_API_KEY,
    BING_ENDPOINT: process.env.BING_ENDPOINT,
    PINECONE_ENVIRONMENT: process.env.PINECONE_ENVIRONMENT,
    PINECONE_API_KEY: process.env.PINECONE_API_KEY,
    PINECONE_INDEX_NAME: process.env.PINECONE_INDEX_NAME,
    PINECONE_NAMESPACE: process.env.PINECONE_NAMESPACE,
    SCREENSHOT_API: process.env.SCREENSHOT_API,
    SCREENSHOT_SECRET: process.env.SCREENSHOT_SECRET,
    SCREENSHOT_ENABLED: process.env.SCREENSHOT_ENABLED,
  },
})
